[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.3"
tag_format = "v$version"
version_files = [
  "kindle-notes-gui/Cargo.toml:^version",
  "kindle-notes-core/Cargo.toml:^version",
  "kindle-notes-cli/Cargo.toml:^version",
]
